version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    restart: unless-stopped
volumes:
  node_modules: